//! Concrete Syntax Tree types
//!
//! Generated by tyrano-parser-generator.

use std::fmt;

/// Unique identifier for a production rule
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ProductionId(pub u32);

/// Unique identifier for a grammar symbol
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SymbolId(pub u32);

/// Source location span
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Span {
    pub start: usize,
    pub end: usize,
}

impl Span {
    pub fn new(start: usize, end: usize) -> Self {
        Self { start, end }
    }

    pub fn merge(self, other: Span) -> Span {
        Span {
            start: self.start.min(other.start),
            end: self.end.max(other.end),
        }
    }
}

/// CST Node representing either a terminal (token) or non-terminal
#[derive(Debug, Clone)]
pub enum CstNode {
    /// Terminal node (token leaf)
    Terminal {
        symbol_id: SymbolId,
        lexeme: String,
        span: Span,
    },
    /// Non-terminal node (production)
    NonTerminal {
        production_id: ProductionId,
        symbol_id: SymbolId,
        children: Vec<CstNode>,
        span: Span,
    },
}

impl CstNode {
    /// Create a new terminal node
    pub fn terminal(symbol_id: SymbolId, lexeme: String, span: Span) -> Self {
        CstNode::Terminal {
            symbol_id,
            lexeme,
            span,
        }
    }

    /// Create a new non-terminal node
    pub fn non_terminal(
        production_id: ProductionId,
        symbol_id: SymbolId,
        children: Vec<CstNode>,
    ) -> Self {
        let span = if children.is_empty() {
            Span::new(0, 0)
        } else {
            let first = children.first().unwrap().span();
            let last = children.last().unwrap().span();
            first.merge(last)
        };
        CstNode::NonTerminal {
            production_id,
            symbol_id,
            children,
            span,
        }
    }

    /// Get the span of this node
    pub fn span(&self) -> Span {
        match self {
            CstNode::Terminal { span, .. } => *span,
            CstNode::NonTerminal { span, .. } => *span,
        }
    }

    /// Get the symbol ID of this node
    pub fn symbol_id(&self) -> SymbolId {
        match self {
            CstNode::Terminal { symbol_id, .. } => *symbol_id,
            CstNode::NonTerminal { symbol_id, .. } => *symbol_id,
        }
    }
}

impl fmt::Display for CstNode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.fmt_indent(f, 0)
    }
}

impl CstNode {
    fn fmt_indent(&self, f: &mut fmt::Formatter<'_>, indent: usize) -> fmt::Result {
        let pad = "  ".repeat(indent);
        match self {
            CstNode::Terminal { symbol_id, lexeme, span } => {
                writeln!(f, "{}Terminal(id={}, lexeme={:?}, span={}..{})", 
                    pad, symbol_id.0, lexeme, span.start, span.end)
            }
            CstNode::NonTerminal { production_id, symbol_id, children, span } => {
                writeln!(f, "{}NonTerminal(prod={}, sym={}, span={}..{})", 
                    pad, production_id.0, symbol_id.0, span.start, span.end)?;
                for child in children {
                    child.fmt_indent(f, indent + 1)?;
                }
                Ok(())
            }
        }
    }
}
