//! Grammar metadata for CFG tracking
//!
//! Generated by tyrano-parser-generator.

/// Production rule metadata
#[derive(Debug, Clone)]
pub struct ProductionMeta {
    pub id: u32,
    pub lhs: &'static str,
    pub rhs: &'static [&'static str],
}

/// Symbol metadata
#[derive(Debug, Clone)]
pub struct SymbolMeta {
    pub id: u32,
    pub name: &'static str,
    pub is_terminal: bool,
}

/// All grammar symbols
pub static SYMBOLS: &[SymbolMeta] = &[
    SymbolMeta { id: 0, name: "ASTERISK", is_terminal: true },
    SymbolMeta { id: 1, name: "AT", is_terminal: true },
    SymbolMeta { id: 2, name: "BLOCK_COMMENT_END", is_terminal: true },
    SymbolMeta { id: 3, name: "BLOCK_COMMENT_START", is_terminal: true },
    SymbolMeta { id: 4, name: "COLON", is_terminal: true },
    SymbolMeta { id: 5, name: "ENTITY", is_terminal: true },
    SymbolMeta { id: 6, name: "EQUAL", is_terminal: true },
    SymbolMeta { id: 7, name: "HTML_END", is_terminal: true },
    SymbolMeta { id: 8, name: "HTML_START", is_terminal: true },
    SymbolMeta { id: 9, name: "HTML_TEXT", is_terminal: true },
    SymbolMeta { id: 10, name: "IDENTIFIER", is_terminal: true },
    SymbolMeta { id: 11, name: "ISCRIPT_END", is_terminal: true },
    SymbolMeta { id: 12, name: "ISCRIPT_START", is_terminal: true },
    SymbolMeta { id: 13, name: "LBRACKET", is_terminal: true },
    SymbolMeta { id: 14, name: "LINE_COMMENT", is_terminal: true },
    SymbolMeta { id: 15, name: "NEWLINE", is_terminal: true },
    SymbolMeta { id: 16, name: "NUMBER", is_terminal: true },
    SymbolMeta { id: 17, name: "PARAM_REF", is_terminal: true },
    SymbolMeta { id: 18, name: "PIPE", is_terminal: true },
    SymbolMeta { id: 19, name: "RBRACKET", is_terminal: true },
    SymbolMeta { id: 20, name: "SCRIPT_TEXT", is_terminal: true },
    SymbolMeta { id: 21, name: "SHARP", is_terminal: true },
    SymbolMeta { id: 22, name: "STRING", is_terminal: true },
    SymbolMeta { id: 23, name: "TEXT", is_terminal: true },
    SymbolMeta { id: 24, name: "UNDERSCORE", is_terminal: true },
    SymbolMeta { id: 25, name: "$", is_terminal: true },
    SymbolMeta { id: 26, name: "block_comment_end", is_terminal: false },
    SymbolMeta { id: 27, name: "block_comment_start", is_terminal: false },
    SymbolMeta { id: 28, name: "bracket_tag", is_terminal: false },
    SymbolMeta { id: 29, name: "chara_spec", is_terminal: false },
    SymbolMeta { id: 30, name: "character_name", is_terminal: false },
    SymbolMeta { id: 31, name: "html_block", is_terminal: false },
    SymbolMeta { id: 32, name: "html_content", is_terminal: false },
    SymbolMeta { id: 33, name: "iscript_block", is_terminal: false },
    SymbolMeta { id: 34, name: "label", is_terminal: false },
    SymbolMeta { id: 35, name: "label_spec", is_terminal: false },
    SymbolMeta { id: 36, name: "line", is_terminal: false },
    SymbolMeta { id: 37, name: "line_comment", is_terminal: false },
    SymbolMeta { id: 38, name: "line_list", is_terminal: false },
    SymbolMeta { id: 39, name: "mixed_content", is_terminal: false },
    SymbolMeta { id: 40, name: "param_name", is_terminal: false },
    SymbolMeta { id: 41, name: "parameter", is_terminal: false },
    SymbolMeta { id: 42, name: "parameter_list", is_terminal: false },
    SymbolMeta { id: 43, name: "parameter_value", is_terminal: false },
    SymbolMeta { id: 44, name: "scenario", is_terminal: false },
    SymbolMeta { id: 45, name: "script_content", is_terminal: false },
    SymbolMeta { id: 46, name: "tag_at", is_terminal: false },
    SymbolMeta { id: 47, name: "tag_content", is_terminal: false },
    SymbolMeta { id: 48, name: "text_line", is_terminal: false },
    SymbolMeta { id: 49, name: "text_segment", is_terminal: false },
];

/// All production rules
pub static PRODUCTIONS: &[ProductionMeta] = &[
    ProductionMeta { id: 0, lhs: "scenario", rhs: &["line_list"] },
    ProductionMeta { id: 1, lhs: "line_list", rhs: &[] },
    ProductionMeta { id: 2, lhs: "line_list", rhs: &["line_list", "line"] },
    ProductionMeta { id: 3, lhs: "line_list", rhs: &["line_list", "NEWLINE"] },
    ProductionMeta { id: 4, lhs: "line", rhs: &["block_comment_start"] },
    ProductionMeta { id: 5, lhs: "line", rhs: &["block_comment_end"] },
    ProductionMeta { id: 6, lhs: "line", rhs: &["line_comment"] },
    ProductionMeta { id: 7, lhs: "line", rhs: &["character_name"] },
    ProductionMeta { id: 8, lhs: "line", rhs: &["label"] },
    ProductionMeta { id: 9, lhs: "line", rhs: &["tag_at"] },
    ProductionMeta { id: 10, lhs: "line", rhs: &["iscript_block"] },
    ProductionMeta { id: 11, lhs: "line", rhs: &["html_block"] },
    ProductionMeta { id: 12, lhs: "line", rhs: &["text_line"] },
    ProductionMeta { id: 13, lhs: "block_comment_start", rhs: &["BLOCK_COMMENT_START"] },
    ProductionMeta { id: 14, lhs: "block_comment_end", rhs: &["BLOCK_COMMENT_END"] },
    ProductionMeta { id: 15, lhs: "line_comment", rhs: &["LINE_COMMENT"] },
    ProductionMeta { id: 16, lhs: "character_name", rhs: &["SHARP", "chara_spec"] },
    ProductionMeta { id: 17, lhs: "character_name", rhs: &["SHARP"] },
    ProductionMeta { id: 18, lhs: "chara_spec", rhs: &["TEXT"] },
    ProductionMeta { id: 19, lhs: "chara_spec", rhs: &["TEXT", "COLON"] },
    ProductionMeta { id: 20, lhs: "chara_spec", rhs: &["TEXT", "COLON", "TEXT"] },
    ProductionMeta { id: 21, lhs: "chara_spec", rhs: &["COLON"] },
    ProductionMeta { id: 22, lhs: "chara_spec", rhs: &["COLON", "TEXT"] },
    ProductionMeta { id: 23, lhs: "label", rhs: &["ASTERISK", "label_spec"] },
    ProductionMeta { id: 24, lhs: "label", rhs: &["ASTERISK"] },
    ProductionMeta { id: 25, lhs: "label_spec", rhs: &["TEXT"] },
    ProductionMeta { id: 26, lhs: "label_spec", rhs: &["TEXT", "PIPE"] },
    ProductionMeta { id: 27, lhs: "label_spec", rhs: &["TEXT", "PIPE", "TEXT"] },
    ProductionMeta { id: 28, lhs: "label_spec", rhs: &["PIPE"] },
    ProductionMeta { id: 29, lhs: "label_spec", rhs: &["PIPE", "TEXT"] },
    ProductionMeta { id: 30, lhs: "tag_at", rhs: &["AT", "tag_content"] },
    ProductionMeta { id: 31, lhs: "text_line", rhs: &["UNDERSCORE"] },
    ProductionMeta { id: 32, lhs: "text_line", rhs: &["UNDERSCORE", "mixed_content"] },
    ProductionMeta { id: 33, lhs: "text_line", rhs: &["mixed_content"] },
    ProductionMeta { id: 34, lhs: "mixed_content", rhs: &["text_segment"] },
    ProductionMeta { id: 35, lhs: "mixed_content", rhs: &["bracket_tag"] },
    ProductionMeta { id: 36, lhs: "mixed_content", rhs: &["mixed_content", "text_segment"] },
    ProductionMeta { id: 37, lhs: "mixed_content", rhs: &["mixed_content", "bracket_tag"] },
    ProductionMeta { id: 38, lhs: "bracket_tag", rhs: &["LBRACKET", "tag_content", "RBRACKET"] },
    ProductionMeta { id: 39, lhs: "tag_content", rhs: &["IDENTIFIER", "parameter_list"] },
    ProductionMeta { id: 40, lhs: "parameter_list", rhs: &[] },
    ProductionMeta { id: 41, lhs: "parameter_list", rhs: &["parameter_list", "parameter"] },
    ProductionMeta { id: 42, lhs: "parameter_list", rhs: &["parameter_list", "ASTERISK"] },
    ProductionMeta { id: 43, lhs: "parameter", rhs: &["param_name", "EQUAL", "parameter_value"] },
    ProductionMeta { id: 44, lhs: "parameter", rhs: &["param_name", "EQUAL"] },
    ProductionMeta { id: 45, lhs: "parameter", rhs: &["param_name"] },
    ProductionMeta { id: 46, lhs: "param_name", rhs: &["IDENTIFIER"] },
    ProductionMeta { id: 47, lhs: "parameter_value", rhs: &["STRING"] },
    ProductionMeta { id: 48, lhs: "parameter_value", rhs: &["NUMBER"] },
    ProductionMeta { id: 49, lhs: "parameter_value", rhs: &["TEXT"] },
    ProductionMeta { id: 50, lhs: "parameter_value", rhs: &["ENTITY"] },
    ProductionMeta { id: 51, lhs: "parameter_value", rhs: &["PARAM_REF"] },
    ProductionMeta { id: 52, lhs: "text_segment", rhs: &["TEXT"] },
    ProductionMeta { id: 53, lhs: "iscript_block", rhs: &["ISCRIPT_START", "script_content", "ISCRIPT_END"] },
    ProductionMeta { id: 54, lhs: "script_content", rhs: &[] },
    ProductionMeta { id: 55, lhs: "script_content", rhs: &["script_content", "SCRIPT_TEXT"] },
    ProductionMeta { id: 56, lhs: "script_content", rhs: &["script_content", "NEWLINE"] },
    ProductionMeta { id: 57, lhs: "html_block", rhs: &["HTML_START", "html_content", "HTML_END"] },
    ProductionMeta { id: 58, lhs: "html_content", rhs: &[] },
    ProductionMeta { id: 59, lhs: "html_content", rhs: &["html_content", "HTML_TEXT"] },
    ProductionMeta { id: 60, lhs: "html_content", rhs: &["html_content", "NEWLINE"] },
];

/// Get production metadata by ID
pub fn get_production(id: u32) -> Option<&'static ProductionMeta> {
    PRODUCTIONS.get(id as usize)
}

/// Get symbol metadata by ID
pub fn get_symbol(id: u32) -> Option<&'static SymbolMeta> {
    SYMBOLS.get(id as usize)
}

/// Find symbol ID by name
pub fn find_symbol_id(name: &str) -> Option<u32> {
    SYMBOLS.iter().find(|s| s.name == name).map(|s| s.id)
}
