//! Table-driven LALR(1) parser
//!
//! Generated by tyrano-parser-generator.

use crate::cst::{CstNode, ProductionId, SymbolId, Span};
use crate::tables::{Action, get_action, get_goto, get_production_info, get_symbol_name};

/// Parser error
#[derive(Debug, Clone)]
pub struct ParseError {
    pub message: String,
    pub span: Span,
    pub expected: Vec<String>,
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for ParseError {}

/// Token from lexer
#[derive(Debug, Clone)]
pub struct Token {
    pub symbol_id: u32,
    pub lexeme: String,
    pub span: Span,
}

impl Token {
    pub fn new(symbol_id: u32, lexeme: String, start: usize, end: usize) -> Self {
        Self {
            symbol_id,
            lexeme,
            span: Span::new(start, end),
        }
    }

    pub fn eof(position: usize) -> Self {
        Self {
            symbol_id: EOF_SYMBOL_ID,
            lexeme: String::new(),
            span: Span::new(position, position),
        }
    }
}

/// EOF symbol ID (must match tables.rs)
const EOF_SYMBOL_ID: u32 = {
    // This should be set based on the grammar's terminal count
    // For now, use a placeholder that will be updated
    crate::tables::terminals::EOF
};

/// LALR(1) Parser
pub struct Parser;

impl Parser {
    /// Parse a sequence of tokens into a CST
    pub fn parse(tokens: Vec<Token>) -> Result<CstNode, ParseError> {
        let mut state_stack: Vec<u32> = vec![0];
        let mut value_stack: Vec<CstNode> = Vec::new();
        let mut token_iter = tokens.into_iter().peekable();

        loop {
            let state = *state_stack.last().unwrap();
            let token = token_iter.peek().cloned().unwrap_or_else(|| Token::eof(0));
            
            match get_action(state, token.symbol_id) {
                Action::Shift(next_state) => {
                    state_stack.push(next_state);
                    
                    // Create terminal CST node
                    let node = CstNode::terminal(
                        SymbolId(token.symbol_id),
                        token.lexeme.clone(),
                        token.span,
                    );
                    value_stack.push(node);
                    
                    token_iter.next();
                }
                
                Action::Reduce(production_id) => {
                    let (lhs_id, rhs_len) = get_production_info(production_id)
                        .ok_or_else(|| ParseError {
                            message: format!("Invalid production ID: {}", production_id),
                            span: token.span,
                            expected: vec![],
                        })?;
                    
                    // Pop states
                    for _ in 0..rhs_len {
                        state_stack.pop();
                    }
                    
                    // Pop values and collect children
                    let mut children = Vec::new();
                    for _ in 0..rhs_len {
                        if let Some(node) = value_stack.pop() {
                            children.push(node);
                        }
                    }
                    children.reverse();
                    
                    // Create non-terminal node
                    let new_node = CstNode::non_terminal(
                        ProductionId(production_id),
                        SymbolId(lhs_id),
                        children,
                    );
                    value_stack.push(new_node);
                    
                    // Goto
                    let current_state = *state_stack.last().unwrap();
                    let goto_state = get_goto(current_state, lhs_id)
                        .ok_or_else(|| ParseError {
                            message: format!(
                                "No goto for state {} and symbol {}",
                                current_state,
                                get_symbol_name(lhs_id)
                            ),
                            span: token.span,
                            expected: vec![],
                        })?;
                    state_stack.push(goto_state);
                }
                
                Action::Accept => {
                    return value_stack.pop().ok_or_else(|| ParseError {
                        message: "Empty value stack on accept".to_string(),
                        span: Span::new(0, 0),
                        expected: vec![],
                    });
                }
                
                Action::Error => {
                    // Collect expected tokens for this state
                    let expected = collect_expected_tokens(state);
                    
                    return Err(ParseError {
                        message: format!(
                            "Unexpected token '{}' (symbol {}) in state {}",
                            token.lexeme,
                            get_symbol_name(token.symbol_id),
                            state
                        ),
                        span: token.span,
                        expected,
                    });
                }
            }
        }
    }
}

/// Collect expected tokens for error reporting
fn collect_expected_tokens(state: u32) -> Vec<String> {
    crate::tables::get_expected_tokens_for_state(state)
        .iter()
        .map(|s| (*s).to_string())
        .collect()
}
