//! Audio tags: BGM, sound effects, voice configuration, and audio waits.

use super::{ExtraParams::{Allow, Deny}, TagSpec, opt, optd, req, tag};
use super::ValueKind::{Asset, Boolean, Enum, Number, Text};
use crate::project::AssetKind;

pub(super) const TAGS: &[TagSpec] = &[
    tag(
        "playbgm",
        &[req("storage", Asset(AssetKind::Bgm)), optd("loop", Boolean, "true"), opt("volume", Number)],
        Allow,
        "play background music",
    ),
    tag("stopbgm", &[opt("time", Number)], Allow, "stop the background music"),
    tag(
        "fadeinbgm",
        &[
            req("storage", Asset(AssetKind::Bgm)),
            optd("loop", Boolean, "true"),
            optd("fadein", Boolean, "true"),
            opt("sprite_time", Text),
            optd("html5", Boolean, "false"),
            optd("time", Number, "2000"),
            optd("pause", Boolean, "false"),
            opt("seek", Number),
        ],
        Deny,
        "play background music with a fade-in",
    ),
    tag(
        "fadeoutbgm",
        &[optd("loop", Boolean, "true"), opt("storage", Asset(AssetKind::Bgm)), optd("fadeout", Boolean, "true"), optd("time", Number, "2000")],
        Deny,
        "stop the background music with a fade-out",
    ),
    tag(
        "xchgbgm",
        &[
            req("storage", Asset(AssetKind::Bgm)),
            optd("loop", Boolean, "true"),
            optd("fadein", Boolean, "true"),
            optd("fadeout", Boolean, "true"),
            optd("time", Number, "2000"),
            optd("buf", Number, "0"),
        ],
        Deny,
        "cross-fade from the current background music to a new one",
    ),
    tag(
        "pausebgm",
        &[optd("target", Enum(&["bgm", "se"]), "bgm"), opt("buf", Number), optd("next", Boolean, "true")],
        Deny,
        "pause the currently playing background music",
    ),
    tag(
        "resumebgm",
        &[optd("target", Enum(&["bgm", "se"]), "bgm"), opt("buf", Number), optd("next", Boolean, "true")],
        Deny,
        "resume background music paused by [pausebgm]",
    ),
    tag(
        "bgmopt",
        &[
            opt("volume", Number),
            optd("effect", Boolean, "true"),
            opt("buf", Number),
            opt("tag_volume", Number),
            optd("next", Boolean, "true"),
            opt("time", Number),
            opt("samebgm_restart", Boolean),
        ],
        Deny,
        "change the background music configuration",
    ),
    tag(
        "playse",
        &[req("storage", Asset(AssetKind::Sound)), optd("loop", Boolean, "false"), opt("volume", Number)],
        Allow,
        "play a sound effect",
    ),
    tag("stopse", &[opt("time", Number)], Allow, "stop sound effects"),
    tag(
        "fadeinse",
        &[
            req("storage", Asset(AssetKind::Sound)),
            req("time", Number),
            optd("target", Enum(&["bgm", "se"]), "se"),
            optd("loop", Boolean, "false"),
            opt("volume", Number),
            optd("fadein", Boolean, "true"),
            optd("buf", Number, "0"),
            opt("sprite_time", Text),
            optd("html5", Boolean, "false"),
        ],
        Deny,
        "play a sound effect with a fade-in",
    ),
    tag(
        "fadeoutse",
        &[
            opt("storage", Asset(AssetKind::Sound)),
            optd("target", Enum(&["bgm", "se"]), "se"),
            optd("loop", Boolean, "false"),
            optd("buf", Number, "0"),
            optd("fadeout", Boolean, "true"),
        ],
        Deny,
        "stop a sound effect with a fade-out",
    ),
    tag(
        "pausese",
        &[optd("target", Enum(&["bgm", "se"]), "se"), opt("buf", Number), optd("next", Boolean, "true")],
        Deny,
        "pause the currently playing sound effect",
    ),
    tag(
        "resumese",
        &[optd("target", Enum(&["bgm", "se"]), "se"), opt("buf", Number), optd("next", Boolean, "true")],
        Deny,
        "resume a sound effect paused by [pausese]",
    ),
    tag(
        "seopt",
        &[
            opt("volume", Number),
            optd("effect", Boolean, "true"),
            opt("buf", Number),
            opt("tag_volume", Number),
            optd("next", Boolean, "true"),
        ],
        Deny,
        "change the sound effect configuration",
    ),
    tag(
        "changevol",
        &[optd("target", Enum(&["bgm", "se"]), "bgm"), opt("volume", Number), opt("buf", Number), opt("time", Number), optd("next", Boolean, "true")],
        Deny,
        "change the volume of currently playing audio",
    ),
    tag(
        "popopo",
        &[
            opt("volume", Text),
            opt("time", Number),
            opt("tailtime", Number),
            opt("frequency", Enum(&["A", "A+", "B", "B+", "C", "C+", "D", "D+", "E", "E+", "F", "F+", "G", "G+"])),
            opt("octave", Number),
            opt("type", Enum(&["sine", "square", "sawtooth", "triangle", "noise", "file", "none"])),
            opt("mode", Enum(&["everyone", "interval"])),
            opt("buf", Number),
            opt("storage", Text),
            opt("samplerate", Number),
            optd("chara", Text, "default"),
        ],
        Deny,
        "play a synthesized blip sound alongside displayed text",
    ),
    tag(
        "voconfig",
        &[opt("sebuf", Number), opt("name", Text), opt("vostorage", Text), opt("number", Number), opt("waittime", Number), opt("preload", Boolean)],
        Deny,
        "configure automatic voice playback for a character",
    ),
    tag("vostart", &[], Deny, "start automatic voice playback configured by [voconfig]"),
    tag("vostop", &[], Deny, "stop automatic voice playback"),
    tag("speak_on", &[optd("volume", Number, "100"), optd("pitch", Number, "100"), optd("rate", Number, "100"), optd("cancel", Boolean, "false")], Deny, "enable text-to-speech narration"),
    tag("speak_off", &[opt("volume", Number)], Deny, "disable text-to-speech narration"),
    tag("wbgm", &[], Deny, "wait for background music playback to finish"),
    tag("wse", &[], Deny, "wait for sound effect playback to finish"),
];
