//! 3D tags: the `3d_*` and `obj_model_*` family for the three.js layer.
//!
//! Model/texture/sound storages in this family load from `data/others/3d/...`
//! (models, sprites, textures, audio) — not one of the standard asset dirs —
//! so those params stay [`ValueKind::Text`] to avoid false missing-asset
//! warnings. `pos`/`rot`/`scale` accept either a single number or a
//! comma-separated `x,y,z` triple (engine's `$.three_pos`), so they stay
//! [`ValueKind::Text`] even where the engine default is a single number.

use super::{ExtraParams::{Allow, Deny}, TagSpec, opt, optd, req, tag};
use super::ValueKind::{Asset, Boolean, Color, Enum, Expression, Label, Number, Scenario, Text};
use crate::project::AssetKind;

/// The tween easing keyword set accepted by `3d_anim`'s `effect` parameter
/// (verified against the engine's `:param` doc comment, which enumerates the
/// full list).
const ANIM_EFFECTS: &[&str] = &[
    "swing", "linear", "easeInQuad", "easeOutQuad", "easeInOutQuad", "easeInCubic", "easeOutCubic",
    "easeInOutCubic", "easeInQuart", "easeOutQuart", "easeInOutQuart", "easeInQuint", "easeOutQuint",
    "easeInOutQuint", "easeInSine", "easeOutSine", "easeInOutSine", "easeInExpo", "easeOutExpo",
    "easeInOutExpo", "easeInCirc", "easeOutCirc", "easeInOutCirc", "easeInElastic", "easeOutElastic",
    "easeInOutElastic", "easeInBack", "easeOutBack", "easeInOutBack", "easeInBounce", "easeOutBounce",
    "easeInOutBounce",
];

/// The `THREE.js` material class keyword set accepted by `3d_init`'s and
/// `obj_model_new`'s `material_type` parameters (verified against the
/// engine's `$.getMaterialType` helper).
const MATERIAL_TYPES: &[&str] = &["basic", "normal", "lambert", "phong", "toon", "standard"];

/// The `front`/`back`/`double` texture-side keyword set accepted by several
/// `3d_*_new`/`3d_*_mod`/`obj_model_*` tags' `side` parameter.
const MODEL_SIDES: &[&str] = &["front", "back", "double"];

pub(super) const TAGS: &[TagSpec] = &[
    // --- scene setup, camera, canvas -----------------------------------
    tag(
        "3d_init",
        &[
            opt("layer", Text),
            optd("page", Enum(&["fore", "back"]), "fore"),
            optd("camera", Enum(&["Perspective", "Orthographic"]), "Perspective"),
            optd("near", Number, "10"),
            optd("far", Number, "5000"),
            optd("material_type", Enum(MATERIAL_TYPES), "basic"),
            optd("ambient_light", Number, "1"),
            optd("directional_light", Number, "0"),
            opt("encoding", Text),
            optd("antialias", Boolean, "true"),
            optd("studio", Boolean, "false"),
            opt("fps_rate", Number),
            opt("stats", Boolean),
            optd("background", Boolean, "true"),
            optd("debug_pos", Boolean, "true"),
            opt("xr", Text),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "initialize the 3D scene; required before any other 3d_* tag",
    ),
    tag(
        "3d_scene",
        &[
            opt("tonemap", Enum(&["No", "Linear", "Reinhard", "Uncharted2", "Cineon", "ACESFilmic"])),
            optd("tonemap_value", Number, "0.8"),
            opt("light_amb", Number),
            opt("fog", Boolean),
            optd("fog_range", Text, "1,3000"),
            optd("fog_color", Color, "0xFFFFFF"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "configure scene-wide tone mapping, ambient light, and fog",
    ),
    tag(
        "3d_camera",
        &[opt("pos", Text), opt("rot", Text), opt("lookat", Text), optd("next", Boolean, "true")],
        Allow,
        "set the 3D camera's position, rotation, or look-at target",
    ),
    tag(
        "3d_helper",
        &[opt("name", Text), opt("grid", Text), opt("axes", Text), optd("next", Boolean, "true")],
        Allow,
        "add a grid and axes helper overlay for scene calibration",
    ),
    tag("3d_canvas_show", &[optd("time", Number, "1000")], Deny, "fade the 3D canvas back into view"),
    tag("3d_canvas_hide", &[optd("time", Number, "1000")], Deny, "fade the 3D canvas out of view"),
    tag("3d_close", &[], Deny, "tear down the 3D scene; [3d_init] is required to use 3d_* again"),

    // --- groups ----------------------------------------------------------
    tag("3d_new_group", &[req("name", Text)], Deny, "create a new empty 3D group"),
    tag(
        "3d_add_group",
        &[
            req("name", Text),
            req("group", Text),
            opt("new_name", Text),
            opt("scale", Text),
            opt("pos", Text),
            opt("rot", Text),
            optd("clone", Boolean, "false"),
        ],
        Allow,
        "add a 3D object to a group, optionally cloning it first",
    ),

    // --- model / primitive creation --------------------------------------
    tag(
        "3d_box_new",
        &[
            req("name", Text),
            optd("type", Text, "BoxGeometry"),
            opt("texture", Text),
            optd("color", Color, "0x00ff00"),
            optd("width", Number, "1"),
            optd("height", Number, "1"),
            optd("depth", Number, "1"),
            optd("scale", Text, "1"),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            opt("folder", Text),
        ],
        Allow,
        "define a 3D box model",
    ),
    tag(
        "3d_cylinder_new",
        &[
            req("name", Text),
            optd("type", Text, "CylinderGeometry"),
            opt("texture", Text),
            optd("color", Color, "0x00ff00"),
            optd("width", Number, "5"),
            optd("height", Number, "20"),
            optd("segment", Number, "10"),
            optd("side", Enum(MODEL_SIDES), "front"),
            optd("scale", Text, "1"),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            opt("folder", Text),
        ],
        Allow,
        "define a 3D cylinder model",
    ),
    tag(
        "3d_sphere_new",
        &[
            req("name", Text),
            optd("type", Text, "SphereGeometry"),
            opt("texture", Text),
            optd("color", Color, "0x00ff00"),
            optd("radius", Number, "300"),
            optd("width", Number, "30"),
            optd("height", Number, "30"),
            optd("side", Enum(MODEL_SIDES), "front"),
            optd("scale", Text, "1"),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            opt("folder", Text),
        ],
        Allow,
        "define a 3D sphere model",
    ),
    tag(
        "3d_sprite_new",
        &[
            req("name", Text),
            req("storage", Text),
            opt("scale", Text),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            optd("tonemap", Boolean, "false"),
            optd("next", Boolean, "true"),
            opt("folder", Text),
        ],
        Allow,
        "define a billboard sprite that always faces the camera",
    ),
    tag(
        "3d_image_new",
        &[
            req("name", Text),
            req("width", Number),
            optd("type", Text, "PlaneGeometry"),
            opt("texture", Asset(AssetKind::Image)),
            opt("texture_repeat", Text),
            opt("height", Number),
            opt("width_vertical", Number),
            optd("width_seg", Number, "1"),
            optd("height_seg", Number, "1"),
            optd("scale", Text, "1"),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            optd("doubleside", Boolean, "false"),
            optd("tonemap", Boolean, "false"),
        ],
        Allow,
        "define a flat 3D plane textured with an image",
    ),
    tag(
        "3d_html_new",
        &[
            req("name", Text),
            req("width", Number),
            req("height", Number),
            optd("type", Text, "PlaneGeometry"),
            opt("texture", Text),
            opt("texture_repeat", Text),
            opt("width_vertical", Number),
            optd("width_seg", Number, "1"),
            optd("height_seg", Number, "1"),
            optd("scale", Text, "1"),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            optd("doubleside", Boolean, "false"),
            optd("tonemap", Boolean, "false"),
        ],
        Allow,
        "define a 3D plane hosting embedded HTML content (experimental)",
    ),
    tag(
        "3d_model_new",
        &[
            req("name", Text),
            req("storage", Text),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            optd("scale", Text, "100"),
            optd("tonemap", Boolean, "true"),
            opt("motion", Text),
            optd("next", Boolean, "true"),
            opt("folder", Text),
            opt("cache", Boolean),
            opt("update", Text),
        ],
        Allow,
        "load an external glTF/OBJ 3D model file",
    ),
    tag(
        "obj_model_new",
        &[
            req("name", Text),
            req("type", Text),
            opt("texture", Text),
            opt("texture_repeat", Text),
            opt("color", Color),
            optd("arg1", Number, "1"),
            optd("arg2", Number, "1"),
            optd("arg3", Number, "1"),
            optd("arg4", Number, "1"),
            optd("update", Boolean, "false"),
            opt("scale", Text),
            opt("pos", Text),
            opt("rot", Text),
            opt("side", Enum(MODEL_SIDES)),
            optd("doubleside", Boolean, "false"),
            optd("tonemap", Boolean, "true"),
            opt("material_type", Enum(MATERIAL_TYPES)),
            opt("user_data", Text),
            opt("motion", Text),
            opt("opacity", Number),
            opt("folder", Text),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "define a raw THREE.js geometry primitive (internal to the *_new tags)",
    ),
    tag(
        "3d_point_light_new",
        &[
            req("name", Text),
            req("color", Color),
            optd("scale", Text, "0"),
            optd("pos", Text, "10"),
            optd("rot", Text, "0"),
            optd("power", Number, "1"),
            optd("distance", Number, "500"),
            optd("attenuation", Number, "1"),
            optd("helper", Boolean, "false"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "add a point light source",
    ),
    tag(
        "3d_spot_light_new",
        &[
            req("name", Text),
            req("color", Color),
            optd("scale", Text, "0"),
            optd("pos", Text, "10"),
            optd("rot", Text, "0"),
            opt("target_name", Text),
            optd("power", Number, "5"),
            optd("distance", Number, "2500"),
            optd("attenuation", Number, "1"),
            optd("beam_angle", Number, "6"),
            optd("bokeh", Number, "1"),
            optd("helper", Boolean, "false"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "add a spot light source",
    ),
    tag(
        "3d_text_new",
        &[
            req("name", Text),
            req("text", Text),
            optd("size", Number, "42"),
            opt("color", Color),
            optd("scale", Text, "0"),
            optd("pos", Text, "10"),
            optd("rot", Text, "0"),
            optd("tonemap", Boolean, "false"),
            optd("next", Boolean, "true"),
            optd("face", Text, "sans-serif"),
            optd("sprite", Boolean, "false"),
            opt("folder", Text),
        ],
        Allow,
        "draw 3D text rendered onto a plane or sprite",
    ),
    tag(
        "3d_text_new_old",
        &[
            req("name", Text),
            req("text", Text),
            optd("size", Number, "42"),
            optd("canvas_width", Number, "1500"),
            optd("canvas_height", Number, "100"),
            opt("color", Color),
            optd("width", Number, "5"),
            optd("height", Number, "5"),
            optd("scale", Text, "0"),
            optd("pos", Text, "0"),
            optd("rot", Text, "0"),
            optd("tonemap", Boolean, "false"),
            optd("next", Boolean, "true"),
            optd("sprite", Boolean, "false"),
            opt("folder", Text),
        ],
        Allow,
        "draw 3D text (deprecated, canvas-texture implementation)",
    ),
    tag(
        "3d_bg360",
        &[
            req("name", Text),
            req("texture", Text),
            opt("folder", Text),
            optd("scale", Text, "0"),
            optd("pos", Text, "10"),
            optd("rot", Text, "0"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "wrap an equirectangular image around the scene as a 360 background",
    ),
    tag(
        "3d_bg360_video",
        &[
            req("name", Text),
            req("texture", Asset(AssetKind::Video)),
            opt("folder", Text),
            optd("scale", Text, "0"),
            optd("pos", Text, "10"),
            optd("rot", Text, "0"),
            optd("auto", Boolean, "true"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "wrap a 360 video around the scene as an animated background",
    ),

    // --- model / lifecycle modification -----------------------------------
    tag(
        "3d_model_mod",
        &[req("name", Text), opt("type", Text), opt("scale", Text), opt("pos", Text), opt("rot", Text), optd("next", Boolean, "true")],
        Allow,
        "change a loaded 3D model's position, rotation, or scale",
    ),
    tag(
        "obj_model_mod",
        &[
            req("name", Text),
            opt("jname", Text),
            opt("type", Text),
            opt("texture", Text),
            opt("texture_repeat", Text),
            opt("side", Enum(MODEL_SIDES)),
            opt("doubleside", Boolean),
            opt("storage", Text),
            opt("folder", Text),
            optd("texture_reload", Boolean, "true"),
            opt("scale", Text),
            opt("pos", Text),
            opt("rot", Text),
            opt("width", Number),
            opt("height", Number),
            opt("depth", Number),
            opt("color", Color),
            opt("visible", Boolean),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "change a raw THREE.js geometry primitive's texture or transform",
    ),
    tag(
        "3d_sprite_mod",
        &[
            req("name", Text),
            opt("jname", Text),
            opt("type", Text),
            opt("texture", Text),
            opt("texture_repeat", Text),
            opt("storage", Text),
            optd("texture_reload", Boolean, "true"),
            opt("scale", Text),
            opt("pos", Text),
            opt("rot", Text),
            opt("width", Number),
            opt("height", Number),
            opt("depth", Number),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "change a billboard sprite's texture or transform",
    ),
    tag(
        "3d_text_mod",
        &[
            req("name", Text),
            opt("text", Text),
            optd("size", Number, "42"),
            opt("color", Color),
            optd("scale", Text, "0"),
            optd("pos", Text, "10"),
            optd("rot", Text, "0"),
            optd("tonemap", Boolean, "false"),
            optd("next", Boolean, "true"),
            optd("face", Text, "sans-serif"),
            optd("sprite", Boolean, "false"),
            opt("folder", Text),
        ],
        Allow,
        "change a 3D text object's content or style",
    ),
    tag(
        "3d_text_mod_old",
        &[
            req("name", Text),
            opt("jname", Text),
            opt("text", Text),
            opt("size", Number),
            optd("canvas_width", Number, "1500"),
            optd("canvas_height", Number, "100"),
            opt("color", Color),
            opt("scale", Text),
            opt("pos", Text),
            opt("rot", Text),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "change a 3D text object's content (deprecated, canvas-texture implementation)",
    ),
    tag(
        "3d_motion",
        &[req("name", Text), req("motion", Text)],
        Deny,
        "switch a 3D model's playing animation clip",
    ),
    tag(
        "3d_clone",
        &[req("name", Text), optd("time", Number, "500"), opt("scale", Text), opt("pos", Text), opt("rot", Text)],
        Allow,
        "duplicate a 3D object into a new instance",
    ),
    tag(
        "3d_show",
        &[
            req("name", Text),
            optd("group", Text, "default"),
            opt("group_uuid", Text),
            optd("time", Number, "0"),
            optd("scene_add", Boolean, "false"),
            opt("scale", Text),
            opt("pos", Text),
            opt("rot", Text),
            optd("force_sprite", Boolean, "false"),
            optd("wait", Boolean, "true"),
            optd("collision", Boolean, "true"),
            optd("opacity", Number, "1"),
            optd("visible", Boolean, "true"),
        ],
        Allow,
        "show a defined 3D object in the scene",
    ),
    tag(
        "3d_hide",
        &[req("name", Text), optd("time", Number, "500"), optd("next", Boolean, "true"), optd("wait", Boolean, "true")],
        Deny,
        "hide a shown 3D object without deleting its definition",
    ),
    tag(
        "3d_hide_all",
        &[optd("time", Number, "500"), optd("wait", Boolean, "true")],
        Deny,
        "hide every shown 3D object without deleting their definitions",
    ),
    tag(
        "3d_delete",
        &[req("name", Text), optd("scene", Boolean, "false"), optd("next", Boolean, "true")],
        Deny,
        "delete a 3D object's definition entirely",
    ),
    tag("3d_delete_all", &[], Deny, "delete every 3D object's definition"),

    // --- animation ---------------------------------------------------------
    tag(
        "3d_anim",
        &[
            req("name", Text),
            optd("time", Number, "1000"),
            optd("effect", Enum(ANIM_EFFECTS), "linear"),
            opt("pos", Text),
            opt("rot", Text),
            opt("scale", Text),
            optd("walk", Boolean, "false"),
            opt("lookat", Text),
            opt("callback", Text),
            optd("relative", Boolean, "false"),
            optd("loop", Text, "0"),
            optd("direction", Text, "alternate"),
            optd("wait", Boolean, "true"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "animate a 3D object's position, rotation, or scale",
    ),
    tag(
        "3d_anim_stop",
        &[req("name", Text), optd("next", Boolean, "true")],
        Deny,
        "stop a 3D object's running animation",
    ),

    // --- sound / video -------------------------------------------------
    tag(
        "3d_sound",
        &[
            opt("name", Text),
            opt("target_name", Text),
            optd("pos", Text, "0,0,0"),
            opt("folder", Text),
            opt("storage", Text),
            optd("loop", Boolean, "false"),
            opt("volume", Number),
            optd("play", Boolean, "true"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "place a positional sound source in the 3D scene",
    ),
    tag(
        "3d_sound_play",
        &[req("name", Text), opt("volume", Number), optd("loop", Boolean, "false"), optd("next", Boolean, "true")],
        Deny,
        "play a defined 3D sound",
    ),
    tag(
        "3d_sound_stop",
        &[req("name", Text), opt("volume", Number), optd("next", Boolean, "true")],
        Deny,
        "stop a playing 3D sound",
    ),
    tag(
        "3d_video_play",
        &[
            req("name", Text),
            opt("texture", Asset(AssetKind::Video)),
            opt("scale", Text),
            opt("pos", Text),
            opt("rot", Text),
            optd("auto", Boolean, "false"),
            optd("loop", Boolean, "true"),
            optd("next", Boolean, "true"),
        ],
        Allow,
        "play a video texture on a 3D object, or stop it if already playing",
    ),

    // --- events ----------------------------------------------------------
    tag(
        "3d_event",
        &[
            req("name", Text),
            optd("type", Enum(&["jump", "eval"]), "jump"),
            opt("exp", Expression),
            opt("storage", Scenario),
            opt("target", Label),
            opt("distance", Number),
            opt("ground", Text),
            optd("mode", Enum(&["click", "collision", "contextmenu"]), "click"),
        ],
        Deny,
        "define a jump or eval event fired when a 3D object is clicked",
    ),
    tag("3d_event_delete", &[req("name", Text)], Deny, "remove a 3D object's defined event"),
    tag("3d_event_start", &[], Deny, "start accepting 3D events"),
    tag("3d_event_stop", &[], Deny, "stop accepting 3D events"),

    // --- debug tools -------------------------------------------------------
    tag(
        "3d_debug",
        &[
            req("name", Text),
            optd("button_text", Text, "閉"),
            optd("menu", Boolean, "true"),
            optd("overlap", Boolean, "false"),
            optd("reset", Boolean, "false"),
            optd("control", Boolean, "false"),
            optd("orbit", Boolean, "true"),
        ],
        Deny,
        "open an interactive drag-and-drop inspector for a 3D object",
    ),
    tag(
        "3d_debug_bk",
        &[
            req("name", Text),
            optd("button_text", Text, "3Dインスペクタを閉じる"),
            optd("menu", Boolean, "true"),
            optd("overlap", Boolean, "false"),
            optd("reset", Boolean, "false"),
        ],
        Deny,
        "open an interactive drag-and-drop inspector for a 3D object (legacy)",
    ),
    tag(
        "3d_debug_camera",
        &[
            optd("name", Text, "camera"),
            optd("button_text", Text, "カメラインスペクタを閉じる"),
            optd("menu", Boolean, "true"),
            optd("menu_close", Boolean, "true"),
            optd("rotate", Boolean, "true"),
            optd("move", Boolean, "true"),
        ],
        Deny,
        "open an interactive drag-and-drop inspector for the 3D camera",
    ),

    // --- gyro / FPS control --------------------------------------------
    tag(
        "3d_gyro",
        &[optd("max_x", Number, "30"), optd("max_y", Number, "30"), optd("mode", Enum(&["rotation", "position"]), "rotation"), optd("next", Boolean, "true")],
        Deny,
        "steer the camera with device tilt or mouse position",
    ),
    tag(
        "3d_gyro_stop",
        &[optd("max_x", Number, "30"), optd("max_y", Number, "30"), optd("frame", Number, "1"), optd("next", Boolean, "true")],
        Deny,
        "stop gyro-driven camera control",
    ),
    tag(
        "3d_fps_control",
        &[opt("joystick", Boolean), opt("camera_pos_y", Number)],
        Deny,
        "enable first-person keyboard/joystick movement control",
    ),
    tag("fps_control_start", &[], Deny, "resume first-person movement control"),
    tag("fps_control_stop", &[], Deny, "pause first-person movement control"),
];
