pub mod cst_codegen;
pub mod grammar_meta_codegen;
pub mod parser_codegen;
pub mod tables_codegen;

use crate::Result;
use crate::generator::ParseTable;
use crate::grammar::GrammarParser;
use std::fs;
use std::path::Path;

/// Orchestrates code generation for the tyrano-parser crate
pub struct ParserGeneratorCodegen<'a> {
    output_dir: &'a Path,
    grammar: &'a GrammarParser,
    parse_table: &'a ParseTable,
}

impl<'a> ParserGeneratorCodegen<'a> {
    pub fn new(
        output_dir: &'a Path,
        grammar: &'a GrammarParser,
        parse_table: &'a ParseTable,
    ) -> Self {
        Self {
            output_dir,
            grammar,
            parse_table,
        }
    }

    /// Generate the complete tyrano-parser crate
    pub fn generate(&self) -> Result<()> {
        // Create output directory structure
        let src_dir = self.output_dir.join("src");
        fs::create_dir_all(&src_dir).map_err(|e| {
            crate::ParserError::GrammarError(format!("Failed to create output directory: {}", e))
        })?;

        // Generate Cargo.toml
        self.generate_cargo_toml()?;

        // Generate lib.rs
        self.generate_lib_rs(&src_dir)?;

        // Generate cst.rs
        cst_codegen::generate(&src_dir, self.grammar)?;

        // Generate grammar_meta.rs
        grammar_meta_codegen::generate(&src_dir, self.grammar)?;

        // Generate tables.rs
        tables_codegen::generate(&src_dir, self.parse_table, self.grammar)?;

        // Generate parser.rs
        parser_codegen::generate(&src_dir, self.grammar)?;

        Ok(())
    }

    fn generate_cargo_toml(&self) -> Result<()> {
        let cargo_toml = r#"[package]
name = "tyrano-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tyrano-lexer = { path = "../tyrano-lexer" }
"#;
        let path = self.output_dir.join("Cargo.toml");
        fs::write(&path, cargo_toml).map_err(|e| {
            crate::ParserError::GrammarError(format!("Failed to write Cargo.toml: {}", e))
        })?;
        Ok(())
    }

    fn generate_lib_rs(&self, src_dir: &Path) -> Result<()> {
        let lib_rs = r#"//! Generated TyranoScript Parser
//!
//! This crate is automatically generated by tyrano-parser-generator.
//! Do not edit manually.

pub mod cst;
pub mod grammar_meta;
pub mod parser;
pub mod tables;

pub use cst::{CstNode, ProductionId, SymbolId, Span};
pub use parser::Parser;
"#;
        let path = src_dir.join("lib.rs");
        fs::write(&path, lib_rs).map_err(|e| {
            crate::ParserError::GrammarError(format!("Failed to write lib.rs: {}", e))
        })?;
        Ok(())
    }
}
