//! Grammar metadata code generation

use crate::Result;
use crate::grammar::GrammarParser;
use std::fs;
use std::path::Path;

/// Generate grammar_meta.rs with CFG tracking metadata
pub fn generate(src_dir: &Path, grammar: &GrammarParser) -> Result<()> {
    let mut code = String::new();

    code.push_str(
        r#"//! Grammar metadata for CFG tracking
//!
//! Generated by tyrano-parser-generator.

/// Production rule metadata
#[derive(Debug, Clone)]
pub struct ProductionMeta {
    pub id: u32,
    pub lhs: &'static str,
    pub rhs: &'static [&'static str],
}

/// Symbol metadata
#[derive(Debug, Clone)]
pub struct SymbolMeta {
    pub id: u32,
    pub name: &'static str,
    pub is_terminal: bool,
}

"#,
    );

    // Generate symbol table
    code.push_str("/// All grammar symbols\n");
    code.push_str("pub static SYMBOLS: &[SymbolMeta] = &[\n");

    let mut symbol_id = 0u32;

    // Add terminals
    for terminal in grammar.get_terminals() {
        let name = terminal.name();
        code.push_str(&format!(
            "    SymbolMeta {{ id: {}, name: \"{}\", is_terminal: true }},\n",
            symbol_id, name
        ));
        symbol_id += 1;
    }

    // Add EOF
    code.push_str(&format!(
        "    SymbolMeta {{ id: {}, name: \"$\", is_terminal: true }},\n",
        symbol_id
    ));
    symbol_id += 1;

    // Add non-terminals
    for non_terminal in grammar.get_non_terminals() {
        let name = non_terminal.name();
        code.push_str(&format!(
            "    SymbolMeta {{ id: {}, name: \"{}\", is_terminal: false }},\n",
            symbol_id, name
        ));
        symbol_id += 1;
    }

    code.push_str("];\n\n");

    // Generate production table
    code.push_str("/// All production rules\n");
    code.push_str("pub static PRODUCTIONS: &[ProductionMeta] = &[\n");

    for production in grammar.get_productions() {
        let lhs = production.lhs.name();
        let rhs: Vec<String> = production
            .rhs
            .iter()
            .filter(|s| !s.is_epsilon())
            .map(|s| format!("\"{}\"", s.name()))
            .collect();

        code.push_str(&format!(
            "    ProductionMeta {{ id: {}, lhs: \"{}\", rhs: &[{}] }},\n",
            production.id,
            lhs,
            rhs.join(", ")
        ));
    }

    code.push_str("];\n\n");

    // Generate helper functions
    code.push_str(
        r#"/// Get production metadata by ID
pub fn get_production(id: u32) -> Option<&'static ProductionMeta> {
    PRODUCTIONS.get(id as usize)
}

/// Get symbol metadata by ID
pub fn get_symbol(id: u32) -> Option<&'static SymbolMeta> {
    SYMBOLS.get(id as usize)
}

/// Find symbol ID by name
pub fn find_symbol_id(name: &str) -> Option<u32> {
    SYMBOLS.iter().find(|s| s.name == name).map(|s| s.id)
}
"#,
    );

    let path = src_dir.join("grammar_meta.rs");
    fs::write(&path, code).map_err(|e| {
        crate::ParserError::GrammarError(format!("Failed to write grammar_meta.rs: {}", e))
    })?;

    Ok(())
}
