//! Parse tables code generation

use crate::Result;
use crate::generator::ParseTable;
use crate::grammar::GrammarParser;
use crate::generator::Action;
use crate::ParserError::GrammarError;
use std::collections::HashMap;
use std::fs;
use std::path::Path;


/// Generate tables.rs with action/goto tables
pub fn generate(src_dir: &Path, parse_table: &ParseTable, grammar: &GrammarParser) -> Result<()> {
    let mut code = String::new();

    code.push_str(
        r#"//! Parse tables (action and goto)
//!
//! Generated by tyrano-parser-generator.

#[allow(unused_imports)]
pub use tyrano_lexer::TokenType;
/// Parser action
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    /// Shift to state
    Shift(u32),
    /// Reduce by production
    Reduce(u32),
    /// Accept input
    Accept,
    /// Error (no valid action)
    Error,
}

"#,
    );

    // Build symbol to ID mapping
    let mut symbol_to_id: HashMap<String, u32> = HashMap::new();
    let mut id = 0u32;

    for terminal in grammar.get_terminals() {
        symbol_to_id.insert(terminal.name().to_string(), id);
        id += 1;
    }
    symbol_to_id.insert("$".to_string(), id);
    id += 1;

    for non_terminal in grammar.get_non_terminals() {
        symbol_to_id.insert(non_terminal.name().to_string(), id);
        id += 1;
    }

    // Generate symbol name constants for clarity
    code.push_str("/// Terminal symbol IDs\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub mod terminals {\n");
    for terminal in grammar.get_terminals() {
        let name = terminal.name();
        if let Some(&id) = symbol_to_id.get(name) {
            code.push_str(&format!(
                "    pub const {}: u32 = {};\n",
                name.to_uppercase(),
                id
            ));
        }
    }
    if let Some(&id) = symbol_to_id.get("$") {
        code.push_str(&format!("    pub const EOF: u32 = {};\n", id));
    }
    code.push_str("}\n\n");

    // Generate symbol name constants for non-terminals
    code.push_str("/// Non-terminal symbol IDs\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub mod non_terminals {\n");
    for non_terminal in grammar.get_non_terminals() {
        let name = non_terminal.name();
        if let Some(&id) = symbol_to_id.get(name) {
            code.push_str(&format!(
                "    pub const {}: u32 = {};\n",
                name.to_uppercase(),
                id
            ));
        }
    }
    code.push_str("}\n\n");

    // Generate function get the name of a terminal symbol by its ID
    code.push_str(
r#"/// Get the name of a terminal symbol by its ID
#[allow(dead_code)]
pub fn token_type_to_id(tt: &TokenType) -> u32 {
    match tt {
        TokenType::Text(_) => terminals::TEXT,
        TokenType::Identifier(_) => terminals::IDENTIFIER,
        TokenType::Number(_) => terminals::NUMBER,
        TokenType::String(_) => terminals::STRING,
        TokenType::ScriptText(_) => terminals::SCRIPT_TEXT,
        TokenType::HtmlText(_) => terminals::HTML_TEXT,
        TokenType::IscriptStart => terminals::ISCRIPT_START,
        TokenType::IscriptEnd => terminals::ISCRIPT_END,
        TokenType::HtmlStart => terminals::HTML_START,
        TokenType::HtmlEnd => terminals::HTML_END,
        TokenType::LineComment(_) => terminals::LINE_COMMENT,
        TokenType::BlockCommentStart => terminals::BLOCK_COMMENT_START,
        TokenType::BlockCommentEnd => terminals::BLOCK_COMMENT_END,
        TokenType::Sharp => terminals::SHARP,
        TokenType::Asterisk => terminals::ASTERISK,
        TokenType::At => terminals::AT,
        TokenType::LBracket => terminals::LBRACKET,
        TokenType::RBracket => terminals::RBRACKET,
        TokenType::Underscore => terminals::UNDERSCORE,
        TokenType::Equal => terminals::EQUAL,
        TokenType::Colon => terminals::COLON,
        TokenType::Pipe => terminals::PIPE,
        TokenType::Newline => terminals::NEWLINE,
        TokenType::Entity(_) => terminals::ENTITY,
        TokenType::ParamRef(_) => terminals::PARAM_REF,
        TokenType::Eof => terminals::EOF,
    }
}

"#);

    // Find max state ID
    let max_state = parse_table
        .action_table
        .keys()
        .map(|(s, _)| *s)
        .max()
        .unwrap_or(0);

    #[allow(unused_variables)]
    let num_states = max_state + 1;
    #[allow(unused_variables)]
    let num_terminals = grammar.get_terminals().len() + 1; // +1 for EOF

    // Generate action table as a function
    code.push_str("/// Get action for state and terminal symbol ID\n");
    code.push_str("#[inline]\n");
    code.push_str("pub fn get_action(state: u32, symbol_id: u32) -> Action {\n");
    code.push_str("    match (state, symbol_id) {\n");

    // Sort entries by (state, symbol_id) for deterministic output
    let mut action_entries: Vec<(usize, u32, String)> = Vec::new();
    for ((state, symbol), action) in &parse_table.action_table {
        let symbol_name = symbol.name();
        if let Some(&sym_id) = symbol_to_id.get(symbol_name) {
            let action_str = match action {
                Action::Shift(s) => format!("Action::Shift({})", s),
                Action::Reduce(p) => format!("Action::Reduce({})", p),
                Action::Accept => "Action::Accept".to_string(),
                Action::Error => "Action::Error".to_string(),
            };
            action_entries.push((*state, sym_id, action_str));
        }
    }
    action_entries.sort_by_key(|(state, sym_id, _)| (*state, *sym_id));
    for (state, sym_id, action_str) in action_entries {
        code.push_str(&format!(
            "        ({}, {}) => {},\n",
            state, sym_id, action_str
        ));
    }

    code.push_str("        _ => Action::Error,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate goto table as a function
    code.push_str("/// Get goto state for state and non-terminal symbol ID\n");
    code.push_str("#[inline]\n");
    code.push_str("pub fn get_goto(state: u32, symbol_id: u32) -> Option<u32> {\n");
    code.push_str("    match (state, symbol_id) {\n");

    // Sort entries by (state, symbol_id) for deterministic output
    let mut goto_entries: Vec<(usize, u32, usize)> = Vec::new();
    for ((state, symbol), next_state) in &parse_table.goto_table {
        let symbol_name = symbol.name();
        if let Some(&sym_id) = symbol_to_id.get(symbol_name) {
            goto_entries.push((*state, sym_id, *next_state));
        }
    }
    goto_entries.sort_by_key(|(state, sym_id, _)| (*state, *sym_id));
    for (state, sym_id, next_state) in goto_entries {
        code.push_str(&format!(
            "        ({}, {}) => Some({}),\n",
            state, sym_id, next_state
        ));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate production info for reduce actions
    code.push_str("/// Production info for reduce actions: (lhs_symbol_id, rhs_length)\n");
    code.push_str("pub fn get_production_info(production_id: u32) -> Option<(u32, usize)> {\n");
    code.push_str("    match production_id {\n");

    for production in grammar.get_productions() {
        let lhs_name = production.lhs.name();
        if let Some(&lhs_id) = symbol_to_id.get(lhs_name) {
            let rhs_len = if production.is_epsilon_production() {
                0
            } else {
                production.rhs.len()
            };
            code.push_str(&format!(
                "        {} => Some(({}, {})),\n",
                production.id, lhs_id, rhs_len
            ));
        }
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate symbol name lookup
    code.push_str("/// Get symbol name by ID\n");
    code.push_str("pub fn get_symbol_name(symbol_id: u32) -> &'static str {\n");
    code.push_str("    match symbol_id {\n");

    // Sort by ID for deterministic output
    let mut symbol_entries: Vec<(u32, &str)> = symbol_to_id
        .iter()
        .map(|(name, &id)| (id, name.as_str()))
        .collect();
    symbol_entries.sort_by_key(|(id, _)| *id);
    for (id, name) in symbol_entries {
        code.push_str(&format!("        {} => \"{}\",\n", id, name));
    }

    code.push_str("        _ => \"<unknown>\",\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate expected tokens for each state (for error reporting)
    // Group actions by state and collect valid (non-error) terminal symbols
    let mut state_to_expected: HashMap<usize, Vec<&str>> = HashMap::new();
    for ((state, symbol), action) in &parse_table.action_table {
        // Only include terminals (not non-terminals) and non-error actions
        if !matches!(action, Action::Error) {
            let symbol_name = symbol.name();
            state_to_expected
                .entry(*state)
                .or_default()
                .push(symbol_name);
        }
    }

    code.push_str("/// Get expected tokens for a state (for error reporting)\n");
    code.push_str(
        "pub fn get_expected_tokens_for_state(state: u32) -> &'static [&'static str] {\n",
    );
    code.push_str("    match state {\n");

    // Sort states for deterministic output
    let mut states: Vec<_> = state_to_expected.keys().copied().collect();
    states.sort();

    for state in states {
        if let Some(symbols) = state_to_expected.get(&state) {
            // Deduplicate and sort symbols
            let mut unique_symbols: Vec<_> = symbols.iter().copied().collect();
            unique_symbols.sort();
            unique_symbols.dedup();

            let symbols_str = unique_symbols
                .iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ");
            code.push_str(&format!("        {} => &[{}],\n", state, symbols_str));
        }
    }

    code.push_str("        _ => &[],\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let path = src_dir.join("tables.rs");
    fs::write(&path, code).map_err(|e| {
        GrammarError(format!("Failed to write tables.rs: {}", e))
    })?;

    Ok(())
}
